name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}  # Fixed: Using SSH_USER instead of SSH_USERNAME
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Fixed: Using SSH_PRIVATE_KEY instead of password
          script: |
            cd /home/${{ secrets.SSH_USER }}/fastapi-book-project || exit

            # Pull the latest code
            git pull origin main

            # Activate virtual environment (if available)
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Restart FastAPI app
            sudo systemctl restart fastapi
