name: CD Pipeline 

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/fastapi-book-project || exit

            # Export environment variables
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            echo "DEBUG=${{ secrets.DEBUG }}" >> .env

            # Pull the latest code
            git pull origin main

            # Activate virtual environment (if you're using one)
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Restart FastAPI app (adjust based on your setup)
            sudo systemctl restart fastapi
